name: Build my frontend angular project
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.3.0'
      - run: npm ci
      - run: npm run build --if-present




#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '23.3.0'
#          cache: 'npm'


#      - name: Build and Push the Created Docker Image to your Docker Repo
#        uses: mr-smithers-excellent/docker-build-push@v6
#        with:
#          image: szymek07/qsl-manager-web
#          tags: latest
#          registry: docker.io
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          dockerfile: Dockerfile


